### ISSUE TITLE
getEnvironment returns incorrect results

### ISSUE THREAD

**Issue by drzax** [abcnews/env-utils#13]
A change to the domain names used for the various preview environments available means that `getEnvironment` is now returning incorrect results for (non-prod) outputs.

The main change is that PL previews have been switched to use the `develop` deployment rather than the `preview` deployment. There is [information about the various PL deployments](https://confluence.abc-dev.net.au/display/CW/Presentation+Layer+Deployments) available. But it all needs to be verified in the real world.

**Comment by drzax** [comment]
I propose we remove `getEnvironment`. I think it was initially added for completeness, but:
- I don't know of any dependencies using it
- It's not currently working
- The need for it is unclear
- The environment can't be detected by hostname as it used to be, so this would require a new detection method — effort that I don't think is necessary.

**Comment by phocks** [comment]
Agree.

**Comment by drzax** [comment]
Removed in #29
