### ISSUE TITLE
Add an 'unknown' tier and positively test for knowns

### ISSUE THREAD

**Issue by drzax** [abcnews/env-utils#2]
Assuming live if it doesn't match the criteria for preview and the inverse of that both have potential issues.

For example, assuming live means that should a new preview URL structure pop up for whatever reason (like they have a lot recently during the transition to PL) means that we'll be assuming live in new preview environments.

On the other hand, if we go the other way we would assume preview on new production URLs that pop up (like they did when the app switched to web views). This could lead to presentation intended for preview only to show up live (this happened with the quiz login form, for example). 

I think the best option would be to perform positive tests for all known tiers and have an 'unknown' tier.

**Comment by colingourlay** [comment]
I love this idea.

It's been rare that we've wanted to positively ID the Live tier in previous projects (more often than not we're trying to ID the Preview tier, so we can do some logging, or talk to Preview Terminus).

I'll get on it.

**Comment by colingourlay** [comment]
Rather than add 'unknown' to the `TIERS` enum, I'm sticking with the method I've used for applications and generations: Unknowns on the get{X} functions will return `null`, leaving us a consistent way to extend the enums when we add new applications, generations and tiers.
