### ISSUE TITLE
requestDOMPermit broken - decoy elements gone from News template

### ISSUE THREAD

**Issue by andrewkesper** [abcnews/env-utils#21]
A recent change to the News story template seems to have removed the decoy elements, breaking the requestDOMPermit function.

However, the decoy elements still exist in the HTML of Odyssey stories. Perhaps Odyssey stories are a special case. But for other stories, requestDOMPermit no longer works.

**Comment by phocks** [comment]
Well that sucks.

**Comment by andrewkesper** [comment]
Yeah. I've been working on a story that overtakes the page using a similar technique to Odyssey. It was working last week and now it's broken. But Odyssey stories are still OK.

**Comment by andrewkesper** [comment]
A very dodgy workaround: append `?news-projects/odyssey/` to the script URL. It tricks the story template into believing it's an Odyssey story. But it will inevitably break.

**Comment by colingourlay** [comment]
Jeeeeez. Well, that seems to be an assumption on the part of News Web that we only depend on decoys for Odysseys. They quietly put out a release on Friday that uses different DOM structures for Odysseys and non-Odysseys, which broke the Odyssey ones anyway (a couple of producers of CAFF stories flipped out upon noticing their stories for the weekend and early this week stopped working). They've had to roll back the Odyssey-article changes in response to see where things went wrong, but must have kept the non-Odyssey article changes. Now that you've raised this issue, it seems clearer what they're trying to do (remove decoy nodes from most stories).

**Comment by drzax** [comment]
Did this change form PL get reverted? I've been aware of the issue vaguely, but not got the full story since I got back.

**Comment by phocks** [comment]
Yes I believe it was reverted.

**Comment by drzax** [comment]
Lets close this then. I got the impression from our chat with them about Odyssey the other day that they now understand this stuff is used in more than just Odyssey, so hopefully we can rely on that API to remain in regular articles.
